PRAGMA foreign_keys = ON;

-- Keep agenda email disabled until outbound email transport is configured.
INSERT INTO settings(key,value,updated_at) VALUES('agenda_email_enabled','0',datetime('now'))
ON CONFLICT(key) DO UPDATE SET value='0',updated_at=datetime('now');

INSERT OR REPLACE INTO knowledge_entries(id,category,title,content,language,active,created_at,updated_at) VALUES
('kb-es-contact','contacto','Contacto y ubicación','Dra. Ydania atiende en Av. 3G, Edif. Mini Center Veras Altas, Ground Floor, Local Nº 66-149, sector Las Mercedes, Maracaibo, Edo. Zulia, Z.P. 4002. WhatsApp: +58 424-639-8440. Instagram: @DraYdania. Email: Info@DraYdania.com.','es',1,datetime('now'),datetime('now')),
('kb-es-services','servicios','Áreas de atención','Áreas publicadas: control de peso y metabolismo; medicina estética facial; radiofrecuencia facial; plasma rico en plaquetas (PRP); composición corporal; armonización facial. Toda indicación depende de valoración médica individual.','es',1,datetime('now'),datetime('now')),
('kb-es-weight','servicios','Control de peso y metabolismo','Evaluación clínica individualizada para peso, hábitos, metabolismo y composición corporal. El chatbot no debe prescribir, ajustar medicamentos ni indicar tratamientos personalizados.','es',1,datetime('now'),datetime('now')),
('kb-es-aesthetic','servicios','Medicina estética facial','Opciones médicas orientadas a resultados armónicos y naturales, según anatomía, objetivos y valoración médica. El chatbot puede explicar conceptos generales, no decidir qué tratamiento corresponde a una persona.','es',1,datetime('now'),datetime('now')),
('kb-es-radio','servicios','Radiofrecuencia facial','Tecnología estética no quirúrgica dentro de un plan indicado tras valoración individual. No se debe prometer un resultado específico.','es',1,datetime('now'),datetime('now')),
('kb-es-prp','servicios','PRP','La práctica ofrece valoración para protocolos con plasma rico en plaquetas cuando estén médicamente indicados.','es',1,datetime('now'),datetime('now')),
('kb-es-body','servicios','Composición corporal','Seguimiento de medidas y objetivos de composición corporal como parte de un abordaje integral.','es',1,datetime('now'),datetime('now')),
('kb-es-harmonization','servicios','Armonización facial','Evaluación de proporciones faciales con prioridad en equilibrio, seguridad y naturalidad.','es',1,datetime('now'),datetime('now')),
('kb-es-credentials','credenciales','Trayectoria profesional','Dra. Ydania Karolis Suárez Sansevero es Médico Cirujano, título profesional de 1996. Cuenta con formación superior en Medicina Estética (programa académico de 2 años, 395 horas, 2003–2005), Curso de Posgrado en Obesidad en Universidad Favaloro (2006–2007), cursos internacionales sobre obesidad en San Antonio, Texas (2018) y Crucero de la Ciencia (2019), formación en armonización facial (2020), adicción alimentaria, teoría clínica y abordaje terapéutico (130 horas, 2020–2021) y técnicas de atención al paciente (2020).','es',1,datetime('now'),datetime('now')),
('kb-es-results','seguridad','Resultados y valoración','Los resultados pueden variar entre pacientes. Las imágenes clínicas muestran casos individuales y no garantizan resultados. La indicación de cualquier tratamiento requiere valoración médica.','es',1,datetime('now'),datetime('now')),
('kb-es-booking','citas','Citas','Las citas solicitadas por el sitio quedan pendientes de aprobación del consultorio. La disponibilidad publicada proviene del sistema de agenda; el chatbot nunca debe inventar horarios.','es',1,datetime('now'),datetime('now')),

('kb-en-contact','contact','Contact and location','Dra. Ydania sees patients at Av. 3G, Edif. Mini Center Veras Altas, Ground Floor, Local Nº 66-149, Las Mercedes, Maracaibo, Zulia, Z.P. 4002. WhatsApp: +58 424-639-8440. Instagram: @DraYdania. Email: Info@DraYdania.com.','en',1,datetime('now'),datetime('now')),
('kb-en-services','services','Practice services','Published areas of care include weight and metabolism management, facial aesthetic medicine, facial radiofrequency, platelet-rich plasma (PRP), body composition, and facial harmonization. Any treatment decision requires individualized medical evaluation.','en',1,datetime('now'),datetime('now')),
('kb-en-credentials','credentials','Professional background','Dra. Ydania Karolis Suárez Sansevero is a physician and surgeon, professional degree 1996. Her published training includes higher training in Aesthetic Medicine (2-year academic program, 395 hours, 2003–2005), postgraduate study in Obesity at Universidad Favaloro (2006–2007), international obesity courses in San Antonio, Texas (2018) and Crucero de la Ciencia (2019), facial harmonization training (2020), food addiction theory/clinical management (130 hours, 2020–2021), and patient-care techniques (2020).','en',1,datetime('now'),datetime('now')),
('kb-en-results','safety','Results and evaluation','Results vary between patients. Clinical before-and-after images show individual cases and do not guarantee an outcome. Any treatment requires medical evaluation.','en',1,datetime('now'),datetime('now')),
('kb-en-booking','appointments','Appointments','Appointments requested through the website remain pending until approved by the office. Published availability comes from the scheduling system; the chatbot must never invent appointment times.','en',1,datetime('now'),datetime('now'));
